### ISSUE TITLE
Create accounts for admins in contenful platform

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#10]
Erik, Stan, Stas - should be an admin
Alex, Alessio, David - developers

Create an editor role that admins can manage

**Comment by query-string** [comment]
We will probably need to pay some extra $, because basic Contentful plan includes only 3 users. Also, as I mentioned in Slack – at the moment we are unable to uncheck unnecessary publishing event (such as articles autosave) and as a result deployment webhook fires every time when article changes. I think it is due to Basic plan limitations.
