### ISSUE TITLE
Add domain name for a project

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#11]
domain should be blog.saberespoder.com (Erik will confirm)

**Comment by etavenn** [comment]
@ahemmat @stan2020 @raul any ideas on what our content page domain should be?

I lean towards articulos.saberespoder.com

blog.saberespoder.com
articulos.saberespoder.com
contenido.saberespoder.com

**Comment by stan2020** [comment]
i'd prefer saberespoder.com/finanzas, saberespoder.com/educacion, et al, rather than anything.saberespoder.com.  it's [generally thought to be better for SEO](https://moz.com/community/q/moz-s-official-stance-on-subdomain-vs-subfolder-does-it-need-updating) and that's certainly been my experience. it also looks cleaner, making it easier for users to remember your URL.  and it's a little cleaner for reporting tools like Google Analytics.  but happy to discuss.

**Comment by ahemmat** [comment]
Stan has a good point here if this is an option.

A

**Comment by stan2020** [comment]
sep/[topic] is generally better b/c it's closer to the root, but a close second would be sep/contenido/finanzas or sep/recursos/finanzas.  articles isn't good b/c we'll have videos, polls and other content over time.  i'm not a fan of "blog" b/c we'll offer much more than that, b/c some 3rd-party reporting tools like comscore will literally put you in their "blog/UGC" bucket (undesirable for many advertisers and partners) and b/c for some people the term means unstructured content or a pet column kept by the PR dept of a commerce or software firm.  our content is a core part of our value proposition, by gum!  :)

**Comment by skatkov** [comment]
:(

Our main platform - SEP platform will be hosted on saberespoder.com . That platform will have all the community building and user engaging features.

Content Platform (this project) - is our platform for public outreach, marketing material, for driving traffic to our main platform, boosting SEO rankings and etc. THIS PLATFORM has nothing to do with saberespoder.com and should have a separate DOMAIN. And we need to decide on it here.

Those features you mention here are already built in into CONTENT PLATFORM.

Please, read the documentation 
https://github.com/saberespoder/sepcontent-v2/wiki/Content-Platform
and watch this video:
https://www.youtube.com/watch?v=HBc_9vr3Ojc

If you need me to add sign language narration to that video - then please ask!

**Comment by etavenn** [comment]
@stan2020 @ahemmat 
it would be something.saberespoder.com/[insert different categories like finanzas, salud, etc] so the categories will still be there.

Our overall goal is to deliver products and services through a conversational interface. In this conversational interface we will also provide links to content which will reside in this project which is like our "blog" section. Content is very important added value and a way to boost traffic to our site and raise awareness for our service.

[Operator](https://medium.com/@Operator/growing-our-cross-border-product-ebe72001e697#.qum4uubvs) and [Intercom](https://blog.intercom.com/) have blogs that are not domainName.com/articles. Drippler doesn't have a blog area but that's because their app IS the content site. Some sites that have a similar value prop of connecting people to products, services and "experts" don't even have a blog. Examples are worktoday.com and porch.com.

**Comment by stan2020** [comment]
@skatkov i loved your video the first time i saw it!  i even voted for it for best foreign film at the oscars, but alas we didn't win.  :)

if one of the stated goals of the new site is better SEO, why use a domain that will result in worse SEO?

all of your points are valid from a back-end perspective but the fact that we use different platforms behind the scenes and think of them as different functionalities doesn't need to complicate the URL.  articles, videos and other content aren't just marketing and they're not just us blogging on the side; they bring value to users by answering questions, building brand loyalty and hopefully spurring sharing.  i know we're making the look & feel consistent across all areas of the site, and the domain should be consistent too.  the more unified the user experience the better.

look, i'm frankly more excited about the conversational aspect of the new site than the articles, but if we're going to bother doing online content, let's do it right.

**Comment by skatkov** [comment]
@stan2020 Wait, did you just used a 3 years old article to build your argument against subdomain? I just googled 'subdomain vs subfolder' (and some other variations with 'SEO subdomain') and this link came up first. Are you sure that you know what your talking about? did you read at least 10 pages of that search result ? :-D Do you understand how PageRank works if you trust first link you see in google ? :-D

This subdomain vs subfolder argument is biggest bullshit SEO guys are arguing about. Everyone does their content on separate 3rd level domain (it doesn't make much difference from subfolder), to boost their main domain rankings. Here are services that we use, and guess what? They host content on subdomains!

honeybadger -> does it http://blog.honeybadger.io/
skylight -> does it http://blog.skylight.io/
mixpanel -> does it https://blog.mixpanel.com/
heroku -> does it https://blog.heroku.com/

I can't really believe we're having this argument. There has been so much statements from google and data to back-up that google treats subdomains as part of domains (if they are not some part of subdomain-service wordpress/blogspot type thingy) in last 3 years. Here is a quote from google guy, who advises on PageRank development (John Mueller is his name, look it up in LinkedIn):

> So we recognize that some sites use subdomains as different parts of the site. And, in the same way that other sites might use sub directories.
> 
> With subdomains, the main thing I'd watch out for is that you're not using wildcard subdomains because that can make crawling really, really hard. If we have to go through all of these subdomains and treat them all as separate hosts.
> 
> But if you have a limited number of subdomains then that might be an option.
> 
> Similarly, if you have different sites that are essentially completely separate websites but they're in subdirectories-- so in folders-- then we'll try to figure that out as well. And say, well, actually these are all on the same domain, on the same host name, but these are maybe user-generated content-- like separate sites that should be treated completely separately-- then we'll try to figure that out as well.
> 
> So that's not something that would kind of like improve or hurt rankings. It's more a matter of us figuring that out. And so far I've seen our algorithms do a pretty good job of that.

Please, don't waste my time here. I need a subdomain name, we will not use subfolders! It's a technical limitation.

**Comment by stan2020** [comment]
@skatkov what's the technical limitation?  I may have missed it, but I haven't heard a valid reason yet for not doing subfolders, only your arguments that our internal platforms are different, that there MAY not be much of a difference in SEO and that it's a waste of time to even discuss, which is less of an argument than a bullying tactic.  :)

The downsides I mentioned -- and another I haven't -- are: 
- SEO impact.  There's definitely a debate on this, which means you can google up points of view on both sides.   But I tested both approaches at Internet Brands, eHarmony and OnGreen and found subfolders got better rankings.  If we had just followed the party line that googlies like Mueller and before him Cutts put out there, we wouldn't have had the organic search success we did. 
- Reporting is trickier, [like in GA](http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/). 
- It makes our content look less core to our value proposition.  All of the sites you listed out are B2B software companies, where, as I said, they're blogging on the side b/c it's not their core value offering.  
- It creates a near-existential debate every time you want to add some new section to your site.  For example, if we wanted to build out FarmaSEP on the site, would it warrant a domain or just a subfolder?  Or if we added a bunch of tools -- like calculators to help users evaluate a mortgage, school or car loan -- does that go under the content domain or do we whip out another subdomain?  A subfolder under the core domain?  If we archived our conversation threads and wanted to publish them so that other users could access them, should it go under the core domain or content?  

If you can lay out the tradeoffs for each approach -- or even just itemize the downsides for subfolders --  that would be constructive.  If you've had different experience than me and can lay that out, I'm happy to concede and move on.  Also happy to hop on a skype to discuss!  It's not a religious issue and I know we both just want to do what's best.

**Comment by skatkov** [comment]
domain name : 
http://comunidad.saberespoder.com/

**Comment by query-string** [comment]
@skatkov since it's going to be a completely different name and won't affect any existent logic – can we try to apply this domain for sepcontent.s3-website-us-east-1.amazonaws.com asap?

**Comment by skatkov** [comment]
It was decided to go with **contenido.saberespoder.com** since **comunidad** doesn't properly represent goal of website

**Comment by AmirHemmat** [comment]
Great, I think this is the correct move. Thanks

**Comment by skatkov** [comment]
Done! Project available here -> http://contenido.saberespoder.com

**Comment by query-string** [comment]
Thanks Stas, I feel now I'm almost ready to open a bottle of wine to celebrate )
