### ISSUE TITLE
Replace ad placeholder with real text

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#38]
Here are promotional text for our main platform from @stan2020 

1) Preguntas sobre educación - escuelas locales, clases de inglés, GED? ¡Envíelas a 72237 y obtenga una respuesta directamente a su teléfono!  
2) ¿Sabía usted que puede ganar dinero haciendo horas extras con su teléfono celular? Haga clic aquí para aprender cómo!  
3) ¿Ha escuchado que puede ganar $1, $5, hasta $10 contestando encuestas? Haga clic aquí para aprender cómo!

They should be randomly shown every time page opens

Link should lead to our SEP platform

**Comment by stan2020** [comment]
Sorry, I should've pointed out that promotions 2 and 3 should link to the panelist overview page:  https://content.saberespoder.com/ofertas/Trabajo/como-ser-miembro-del-grupo-de-opinion-de-saberespoder

Promo 1 doesn't actually need to link anywhere since we're encouraging them to text us a question.

Is it possible to vary the links like that, or does every promotion need to link to something and/or the same place?

**Comment by query-string** [comment]
@stan2020 no worries, it doesn't really matter if promotion has to have a link or not – we can vary the links as we want

**Comment by Victoria-Vachevskih** [comment]
verified on production (http://sepcontent.s3-website-us-east-1.amazonaws.com/)
