### ISSUE TITLE
Error 403 appears when some articles are opened

### ISSUE THREAD

**Issue by Victoria-Vachevskih** [saberespoder/contenido#66]
### Steps to reproduce
1. Goto http://sepcontent.s3-website-us-east-1.amazonaws.com/
2. Open any of these articles

The list of broken articles:
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-c1
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-c2
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-c3
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-c4
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-b1
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-b2
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-b3
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/campana-de-momentos-consejo-semana-1-grupo-b4
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/requisitos-para-obtener-su-licencia-de-conducir-la-entrevista-con-el-dmv
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/educaci%C3%B3n/como-prepararse-para-el-examen-practico-de-manejo
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/finanzas/pasos-para-solicitar-un-itin
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/finanzas/como-la-ley-de-cuidado-de-salud-a-bajo-precio-afecta-sus-impuestosabajo
http://sepcontent.s3-website-us-east-1.amazonaws.com/articulos/finanzas/la-voz-de-la-comunidad-a-quienes-puedo-reclamar-como-dependientes

### Expected Result: Articles are opened properly

**Enviroment**
current_user: User

server: http://sepcontent.s3-website-us-east-1.amazonaws.com/

browser: Google Chrome / Safari

operation system: Win 10 / iOS 10

**Comment by query-string** [comment]
I think I have an explanation – I had an impression that all of the articles have slugs that much their titles (e.g. `Estafas comunes de inmigración que debe reconocer` -> `/estafas-comunes-de-inmigracion-que-debe-reconocer`) but it turns out that this statement is not always true: look at the articles listed above – none of them have slugs matching titles (`https://content.saberespoder.com/articulos/finanzas/pasos-para-solicitar-un-itin` != `Pasos para obtener un Número de Identificación Personal del Contribuyente` title from database). 

Luckily, I have saved old slugs on Contentful so for these exceptional cases it will be possible to generate pages based on legacy URLs.
