### ISSUE TITLE
Convert several line breaks into another type of content separator

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#71]
@stan2020 has recently mentioned that Contentful preview ignores several consecutive line breaks and presents them like a single one. Most likely, it happens because of Markdown parser rules and we will have to find a way to convert several `\n` signs. into another type of element for content blocks separation...

**Comment by skatkov** [comment]
What is a use case for this? I can't imagine any valid reason to add multiple line breaks.

**Comment by skatkov** [comment]
Assigning 'wontfix' label for now. I don't see reasons why we should fix this, seems like a very reasonable limitation by markdown.

**Comment by stan2020** [comment]
@skatkov there are times a writer/editor wants more space to emphasize a line / paragraph / point or set off an image.  In general our text is already pretty crowded together, which is not good for readability, esp. on lower brightness that many people set their phones to in order to save battery power.  It's not an urgent priority but it's a basic functionality and definitely one we should add.
